// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt-JKWA3pPMAV5H4RofJ4p-c_HUKC-Yuw',
    appId: '1:244813758252:web:ffed80e00d33be51697689',
    messagingSenderId: '244813758252',
    projectId: 'newpeo-7e512',
    authDomain: 'newpeo-7e512.firebaseapp.com',
    storageBucket: 'newpeo-7e512.firebasestorage.app',
    measurementId: 'G-CGCSGVMRYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsJCA8kL-haqRgqXt2l_RziD-ibL7N8ko',
    appId: '1:244813758252:android:af478d40d6971fe4697689',
    messagingSenderId: '244813758252',
    projectId: 'newpeo-7e512',
    storageBucket: 'newpeo-7e512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoKFUwE6pbp8tmEToo0nbKmJBTACBXdgg',
    appId: '1:244813758252:ios:89674f253e53dc2a697689',
    messagingSenderId: '244813758252',
    projectId: 'newpeo-7e512',
    storageBucket: 'newpeo-7e512.firebasestorage.app',
    iosBundleId: 'com.example.ary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoKFUwE6pbp8tmEToo0nbKmJBTACBXdgg',
    appId: '1:244813758252:ios:89674f253e53dc2a697689',
    messagingSenderId: '244813758252',
    projectId: 'newpeo-7e512',
    storageBucket: 'newpeo-7e512.firebasestorage.app',
    iosBundleId: 'com.example.ary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt-JKWA3pPMAV5H4RofJ4p-c_HUKC-Yuw',
    appId: '1:244813758252:web:4fd3f8a60632d0cd697689',
    messagingSenderId: '244813758252',
    projectId: 'newpeo-7e512',
    authDomain: 'newpeo-7e512.firebaseapp.com',
    storageBucket: 'newpeo-7e512.firebasestorage.app',
    measurementId: 'G-JCNNEH1XKD',
  );
}
